# Generated by Django 3.2.6 on 2021-09-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_contribute_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribute',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='contribute',
            name='list_date',
        ),
    ]
