# Generated by Django 3.2.6 on 2021-09-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20210911_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribute',
            name='title',
            field=models.CharField(help_text='Provide your exact house name', max_length=200),
        ),
    ]
