# Generated by Django 3.2.6 on 2021-09-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_alter_owner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
